feat/search-bar: 달력 스타일 변경 및 검색버튼 기능 구현
YOGIZOGI-Zerobase-2023/FE pull request #67
Opened 2023-06-15 08:59 UTC by Ryomi-j

### PR 타입(하나 이상의 PR 타입을 선택해주세요)

- [ ] 기능 추가
- [ ] 기능 삭제
- [ ] 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 반영 브랜치

feature/search-bar-> dev

### 변경 사항

- 달력 스타일 변경
- 달력 미디어 쿼리 수정
- 검색 버튼 기능 구현
- dynamic routing 사용

2023-06-15 11:17 UTC, cloudedpanther requested changes
- handleSearch function에서 넘겨주는 URL을 올바른 형식으로 수정해주세요.
- App.ts에 /:search, /:detail로 param을 정의한 부분을 삭제해주세요. (search param 혹은 query string이라 불리는 형태로 받을 예정)

2023-06-15 12:41 UTC, cloudedpanther approved these changes

2023-06-16 12:33 UTC, cloudedpanther approved these changes

2023-06-16 14:12 UTC, bbung95 approved these changes

2023-06-16 14:26 UTC, merged